# Generated by Django 3.0.6 on 2020-06-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200604_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
    ]
